INSERT INTO instruments (id, name, name_native, hs_category, hornbostel_sachs, description, origin_region, materials, wikipedia_slug, created_at, updated_at)
VALUES

-- ── South Asia ────────────────────────────────────────────────────────────────
(gen_random_uuid(), 'Tabla', 'तबला', 'Membranophone', '211.212.1', 'A pair of hand drums central to Hindustani classical music, consisting of a small right-hand drum (dayan) and a larger left-hand drum (bayan).', 'South Asia', ARRAY['wood','goat skin','iron'], 'Tabla', now(), now()),
(gen_random_uuid(), 'Sarod', 'सरोद', 'Chordophone', '321.322', 'A fretless lute used in Hindustani classical music, known for its deep, weighty tone and the ability to slide between notes.', 'South Asia', ARRAY['teak','goat skin','steel'], 'Sarod', now(), now()),
(gen_random_uuid(), 'Bansuri', 'बांसुरी', 'Aerophone', '421.121.12', 'A side-blown bamboo flute from the Indian subcontinent, central to both Hindustani classical and folk music.', 'South Asia', ARRAY['bamboo'], 'Bansuri', now(), now()),
(gen_random_uuid(), 'Veena', 'वीणा', 'Chordophone', '321.321', 'One of the oldest Indian string instruments, central to Carnatic classical music. Has a long neck with 24 fixed frets over a large resonating gourd.', 'South Asia', ARRAY['jackwood','bronze'], 'Vina', now(), now()),
(gen_random_uuid(), 'Mridangam', 'மிருதங்கம்', 'Membranophone', '211.212.1', 'The principal percussion instrument of Carnatic music. A double-headed barrel drum played with both hands.', 'South Asia', ARRAY['jackwood','leather'], 'Mridangam', now(), now()),
(gen_random_uuid(), 'Tanpura', 'तानपूरा', 'Chordophone', '321.321', 'A long-necked plucked lute that provides a continuous harmonic drone in Indian classical music. Not played melodically.', 'South Asia', ARRAY['tun wood','gourd'], 'Tanpura', now(), now()),
(gen_random_uuid(), 'Sarangi', 'सारंगी', 'Chordophone', '321.322', 'A bowed string instrument used in Hindustani classical music. Has a short neck, no frets, and up to 40 sympathetic strings.', 'South Asia', ARRAY['cedar','gut'], 'Sarangi', now(), now()),
(gen_random_uuid(), 'Shehnai', 'शहनाई', 'Aerophone', '422.112', 'A double-reed wind instrument associated with auspicious occasions in North India. Related to the oboe family.', 'South Asia', ARRAY['wood','metal'], 'Shehnai', now(), now()),
(gen_random_uuid(), 'Pakhawaj', 'पखावज', 'Membranophone', '211.212.1', 'A large barrel drum used in Dhrupad, the oldest form of Hindustani classical music. Predecessor of the tabla.', 'South Asia', ARRAY['wood','leather'], 'Pakhawaj', now(), now()),
(gen_random_uuid(), 'Harmonium', 'हारमोनियम', 'Aerophone', '412.132', 'A keyboard instrument that produces sound by pushing air through reeds, widely adopted in South Asian music including Qawwali and devotional singing.', 'South Asia', ARRAY['wood','metal reeds'], 'Harmonium', now(), now()),
(gen_random_uuid(), 'Gottuvadyam', 'கொத்துவாத்தியம்', 'Chordophone', '321.321', 'A fretless slide lute of South India used in Carnatic music, played with a cylindrical piece of buffalo horn.', 'South Asia', ARRAY['jackwood'], 'Chitravina', now(), now()),
(gen_random_uuid(), 'Ghatam', 'கடம்', 'Idiophone', '112.12', 'An ancient clay pot percussion instrument used in Carnatic music, played by striking the exterior with fingers and palms.', 'South Asia', ARRAY['clay'], 'Ghatam', now(), now()),

-- ── East Asia ─────────────────────────────────────────────────────────────────
(gen_random_uuid(), 'Guqin', '古琴', 'Chordophone', '312.22', 'A seven-stringed zither and one of the oldest plucked string instruments in China with over 3,000 years of history. Associated with Confucian scholars.', 'East Asia', ARRAY['paulownia wood'], 'Guqin', now(), now()),
(gen_random_uuid(), 'Erhu', '二胡', 'Chordophone', '321.322', 'A two-stringed bowed instrument central to Chinese classical and folk music. Often called the Chinese violin.', 'East Asia', ARRAY['rosewood','python skin','metal'], 'Erhu', now(), now()),
(gen_random_uuid(), 'Pipa', '琵琶', 'Chordophone', '321.321', 'A four-stringed Chinese lute with a pear-shaped body. One of the most important Chinese instruments with over 2,000 years of history.', 'East Asia', ARRAY['paulownia wood','nylon'], 'Pipa', now(), now()),
(gen_random_uuid(), 'Guzheng', '古箏', 'Chordophone', '312.12', 'A 21-string Chinese zither. One of the most popular Chinese instruments, known for its resonant, sweeping sound.', 'East Asia', ARRAY['paulownia wood'], 'Guzheng', now(), now()),
(gen_random_uuid(), 'Shakuhachi', '尺八', 'Aerophone', '421.111.12', 'An end-blown Japanese bamboo flute with five finger holes. Originally used by Buddhist monks as a meditation instrument.', 'East Asia', ARRAY['bamboo'], 'Shakuhachi', now(), now()),
(gen_random_uuid(), 'Koto', '琴', 'Chordophone', '312.12', 'Japan''s national instrument — a 13-string zither played with picks. Central to Gagaku court music.', 'East Asia', ARRAY['paulownia wood'], 'Koto_(instrument)', now(), now()),
(gen_random_uuid(), 'Shamisen', '三味線', 'Chordophone', '321.321', 'A three-stringed Japanese lute with a distinctive buzzing tone. Central to Japanese folk, theatre (kabuki), and narrative music.', 'East Asia', ARRAY['cat skin','dog skin','rosewood'], 'Shamisen', now(), now()),
(gen_random_uuid(), 'Taiko', '太鼓', 'Membranophone', '211.212.1', 'A broad term for Japanese drums. In traditional music, taiko are large barrel drums played with thick wooden sticks (bachi).', 'East Asia', ARRAY['zelkova wood','cowhide'], 'Taiko', now(), now()),
(gen_random_uuid(), 'Biwa', '琵琶', 'Chordophone', '321.321', 'A Japanese short-necked lute. Used in Gagaku court music and as accompaniment to epic oral narratives (biwa hoshi).', 'East Asia', ARRAY['mulberry wood'], 'Biwa', now(), now()),
(gen_random_uuid(), 'Gayageum', '가야금', 'Chordophone', '312.12', 'A traditional Korean 12-string zither, one of the most widely used instruments in Korean classical music (Jeongganbo).', 'East Asia', ARRAY['paulownia wood'], 'Gayageum', now(), now()),
(gen_random_uuid(), 'Haegeum', '해금', 'Chordophone', '321.322', 'A traditional Korean two-stringed fiddle. The only bowed Korean instrument and used in court, folk, and shaman music.', 'East Asia', ARRAY['bamboo','silk'], 'Haegeum', now(), now()),
(gen_random_uuid(), 'Janggu', '장구', 'Membranophone', '211.212.1', 'An hourglass-shaped drum used in Korean folk and court music. The most widely used percussion instrument in Korean music.', 'East Asia', ARRAY['wood','leather'], 'Janggu', now(), now()),

-- ── Southeast Asia ────────────────────────────────────────────────────────────
(gen_random_uuid(), 'Kendang', 'Kendang', 'Membranophone', '211.212.1', 'A double-headed barrel drum central to Gamelan ensembles of Java and Bali. The kendang player leads the ensemble.', 'Southeast Asia', ARRAY['jackwood','cowhide'], 'Kendang', now(), now()),
(gen_random_uuid(), 'Gong Ageng', 'Gong Ageng', 'Idiophone', '111.241.2', 'The largest and most sacred gong in a Gamelan ensemble, struck at key structural moments to mark musical cycles.', 'Southeast Asia', ARRAY['bronze'], 'Gong_ageng', now(), now()),
(gen_random_uuid(), 'Gangsa', 'Gangsa', 'Idiophone', '111.241.2', 'A metallophone from Bali used in Gamelan music, consisting of bronze keys suspended over bamboo resonators.', 'Southeast Asia', ARRAY['bronze','bamboo'], 'Gangsa', now(), now()),
(gen_random_uuid(), 'Kulintang', 'Kulintang', 'Idiophone', '111.241.2', 'A row of small bronze gongs used in the music of Mindanao (Philippines) and Borneo. The heart of kulintang ensemble music.', 'Southeast Asia', ARRAY['bronze'], 'Kulintang', now(), now()),
(gen_random_uuid(), 'Roneat', 'រនាត', 'Idiophone', '111.212', 'A Cambodian xylophone used in the Pinpeat ensemble. The roneat ek (high) and roneat thung (low) provide melodic structure.', 'Southeast Asia', ARRAY['bamboo','wood'], 'Roneat', now(), now()),

-- ── Middle East & North Africa ────────────────────────────────────────────────
(gen_random_uuid(), 'Oud', 'عود', 'Chordophone', '321.321', 'A short-necked, fretless lute central to Arabic, Turkish, and Persian classical music. The ancestor of the European lute.', 'Middle East & North Africa', ARRAY['rosewood','spruce'], 'Oud', now(), now()),
(gen_random_uuid(), 'Qanun', 'قانون', 'Chordophone', '312.12', 'A large zither with 78–81 strings played on the lap. Central to Arabic Maqam and Turkish Makam classical ensembles.', 'Middle East & North Africa', ARRAY['maple','cherry','gut'], 'Qanun_(instrument)', now(), now()),
(gen_random_uuid(), 'Ney', 'ني', 'Aerophone', '421.111.12', 'An end-blown reed flute central to Persian, Turkish, and Arabic classical music. Central to Sufi music and Qawwali.', 'Middle East & North Africa', ARRAY['reed'], 'Ney', now(), now()),
(gen_random_uuid(), 'Darbuka', 'دربوكة', 'Membranophone', '211.261.1', 'A single-headed goblet drum fundamental to Arabic and Turkish music. Also called doumbek.', 'Middle East & North Africa', ARRAY['ceramic','metal','goatskin'], 'Darbuka', now(), now()),
(gen_random_uuid(), 'Santur', 'سنتور', 'Chordophone', '314.122', 'A hammered dulcimer central to Persian classical music. Has 72–92 strings struck with lightweight wooden mallets.', 'Middle East & North Africa', ARRAY['walnut','metal'], 'Santur', now(), now()),
(gen_random_uuid(), 'Tar', 'تار', 'Chordophone', '321.321', 'A long-necked lute central to Persian and Azerbaijani classical music. Has a distinctive figure-eight shaped body.', 'Middle East & North Africa', ARRAY['mulberry','lambskin'], 'Tar_(lute)', now(), now()),
(gen_random_uuid(), 'Daf', 'دف', 'Membranophone', '211.311', 'A large frame drum used across Central Asia, Iran, and South Asia in Sufi and devotional music.', 'Middle East & North Africa', ARRAY['wood','goatskin','metal rings'], 'Daf', now(), now()),
(gen_random_uuid(), 'Saz', 'Saz', 'Chordophone', '321.321', 'A long-necked lute (also called bağlama) fundamental to Turkish folk and Makam music.', 'Middle East & North Africa', ARRAY['mulberry','spruce'], 'Saz', now(), now()),
(gen_random_uuid(), 'Rebab', 'ربابة', 'Chordophone', '321.322', 'A spike fiddle played with a bow, found across the Middle East, North Africa, and Southeast Asia. One of the earliest bowed instruments.', 'Middle East & North Africa', ARRAY['wood','coconut shell','skin'], 'Rebab', now(), now()),
(gen_random_uuid(), 'Kamancheh', 'کمانچه', 'Chordophone', '321.322', 'A spiked fiddle central to Persian, Azerbaijani, and Kurdish classical music. Held vertically and rotated against the bow.', 'Middle East & North Africa', ARRAY['mulberry','horsehair'], 'Kamanche', now(), now()),

-- ── West Africa ───────────────────────────────────────────────────────────────
(gen_random_uuid(), 'Kora', 'Kora', 'Chordophone', '323.6', 'A 21-string West African harp-lute, central to Griot music of the Mandé people. Combines features of a harp and a lute.', 'West Africa', ARRAY['gourd','cowhide','hardwood'], 'Kora_(instrument)', now(), now()),
(gen_random_uuid(), 'Balafon', 'Balafon', 'Idiophone', '111.212', 'A gourd-resonated xylophone played by Griot musicians of West Africa. One of the world''s oldest xylophone-type instruments.', 'West Africa', ARRAY['rosewood','gourd'], 'Balafon', now(), now()),
(gen_random_uuid(), 'Djembe', 'Djembé', 'Membranophone', '211.261.1', 'A goblet-shaped drum from West Africa, central to communal music making across Guinea, Mali, Senegal, and beyond.', 'West Africa', ARRAY['lenke wood','goatskin'], 'Djembe', now(), now()),
(gen_random_uuid(), 'Ngoni', 'Ngoni', 'Chordophone', '321.321', 'A short-necked lute played by Griot musicians across West Africa. An ancestor of the American banjo.', 'West Africa', ARRAY['wood','goatskin'], 'Ngoni', now(), now()),
(gen_random_uuid(), 'Talking Drum', 'Dùndún', 'Membranophone', '211.212.1', 'An hourglass-shaped drum from West Africa whose pitch can be regulated by squeezing the strings, allowing it to mimic tonal languages.', 'West Africa', ARRAY['wood','goatskin'], 'Talking_drum', now(), now()),
(gen_random_uuid(), 'Krin', 'Krin', 'Idiophone', '111.11', 'A slit drum (also called African log drum) from West Africa, used in Griot music and ceremonial contexts.', 'West Africa', ARRAY['wood'], 'Slit_drum', now(), now()),

-- ── East & Southern Africa ────────────────────────────────────────────────────
(gen_random_uuid(), 'Mbira', 'Mbira', 'Idiophone', '122.1', 'A thumb piano from Zimbabwe central to Shona spirit possession ceremonies. Also called kalimba or likembe.', 'Southern Africa', ARRAY['iron tines','wooden board','gourd'], 'Mbira', now(), now()),
(gen_random_uuid(), 'Marimba', 'Marimba', 'Idiophone', '111.212', 'A wooden xylophone with gourd resonators. Central to the music of Zimbabwe, Mozambique, and parts of South America.', 'Southern Africa', ARRAY['wood','gourd'], 'Marimba', now(), now()),
(gen_random_uuid(), 'Ngoma', 'Ngoma', 'Membranophone', '211.212.1', 'A family of single-headed cylindrical drums widespread across Bantu-speaking East and Central Africa.', 'East Africa', ARRAY['wood','cowhide'], 'Ngoma_(drum)', now(), now()),
(gen_random_uuid(), 'Tinde', 'Tinde', 'Aerophone', '422.11', 'A simple flute found in parts of East Africa, used in folk and ceremonial contexts.', 'East Africa', ARRAY['bamboo','wood'], 'Tinde', now(), now()),

-- ── Western Europe ────────────────────────────────────────────────────────────
(gen_random_uuid(), 'Flamenco Guitar', 'Guitarra flamenca', 'Chordophone', '321.322', 'A Spanish guitar built specifically for Flamenco music, typically with a thinner body, lower action, and brighter tone than a classical guitar.', 'Western Europe', ARRAY['cypress','spruce','nylon strings'], 'Flamenco_guitar', now(), now()),
(gen_random_uuid(), 'Cajón', 'Cajón', 'Membranophone', '211.11', 'A box-shaped percussion instrument from Peru adopted as the primary percussion instrument in Flamenco. Played by slapping the front face.', 'South America', ARRAY['plywood'], 'Cajón', now(), now()),
(gen_random_uuid(), 'Uilleann Pipes', 'Píobaí Uilleann', 'Aerophone', '422.112', 'The national bagpipe of Ireland. Unlike Highland pipes, uilleann pipes are bellows-blown and have a softer, complex sound with drones and regulators.', 'Western Europe', ARRAY['wood','leather bellows','metal'], 'Uilleann_pipes', now(), now()),
(gen_random_uuid(), 'Bodhrán', 'Bodhrán', 'Membranophone', '211.311', 'A shallow single-headed frame drum central to Irish traditional music, played with a tipper (bone or wooden beater).', 'Western Europe', ARRAY['wood','goatskin'], 'Bodhrán', now(), now()),
(gen_random_uuid(), 'Tin Whistle', 'Feadóg Stáin', 'Aerophone', '421.211.12', 'A six-holed fipple flute central to Irish and Celtic traditional music. Also called the penny whistle.', 'Western Europe', ARRAY['metal'], 'Tin_whistle', now(), now()),
(gen_random_uuid(), 'Fiddle (Celtic)', 'Fiddle', 'Chordophone', '321.322', 'A violin played in the Celtic tradition of Ireland and Scotland. Technically identical to a classical violin but played with regional bowing styles.', 'Western Europe', ARRAY['spruce','maple','horsehair bow'], 'Celtic_fiddle', now(), now()),
(gen_random_uuid(), 'Bouzouki', 'Μπουζούκι', 'Chordophone', '321.321', 'A long-necked plucked lute central to Greek music. Became central to rebetiko music and later adopted in Irish folk music.', 'Western Europe', ARRAY['maple','spruce'], 'Bouzouki', now(), now()),

-- ── Northern Europe ───────────────────────────────────────────────────────────
(gen_random_uuid(), 'Hardanger Fiddle', 'Hardingfele', 'Chordophone', '321.322', 'A Norwegian folk fiddle with sympathetic strings running beneath the main playing strings, giving it a rich, resonant tone.', 'Northern Europe', ARRAY['spruce','maple'], 'Hardanger_fiddle', now(), now()),
(gen_random_uuid(), 'Nyckelharpa', 'Nyckelharpa', 'Chordophone', '321.322', 'A Swedish keyed fiddle with keys (tangents) that stop the strings. Has sympathetic strings that resonate freely.', 'Northern Europe', ARRAY['spruce','maple'], 'Nyckelharpa', now(), now()),
(gen_random_uuid(), 'Kantele', 'Kantele', 'Chordophone', '312.12', 'The Finnish national instrument — a plucked string instrument and symbol of Finnish national identity. Central to the Kalevala folk tradition.', 'Northern Europe', ARRAY['alder wood'], 'Kantele', now(), now()),

-- ── Eastern Europe & Balkans ──────────────────────────────────────────────────
(gen_random_uuid(), 'Gaida', 'Гайда', 'Aerophone', '422.112', 'A Bulgarian and Macedonian bagpipe fundamental to Balkan folk music. Produces a powerful, penetrating sound.', 'Eastern Europe', ARRAY['goatskin','wood'], 'Gaida', now(), now()),
(gen_random_uuid(), 'Tapan', 'Тапан', 'Membranophone', '211.212.1', 'A large double-headed cylindrical drum played with sticks across the Balkans, especially in Bulgarian and Macedonian folk music.', 'Eastern Europe', ARRAY['wood','goatskin'], 'Tapan', now(), now()),
(gen_random_uuid(), 'Gadulka', 'Гъдулка', 'Chordophone', '321.322', 'A Bulgarian bowed string instrument with a pear-shaped body and sympathetic strings. Central to Balkan folk ensembles.', 'Eastern Europe', ARRAY['maple','spruce'], 'Gadulka', now(), now()),
(gen_random_uuid(), 'Cobza', 'Cobză', 'Chordophone', '321.321', 'A short-necked lute from Romania used in Balkan folk music, closely related to the oud.', 'Eastern Europe', ARRAY['maple','spruce'], 'Cobza', now(), now()),

-- ── South America ─────────────────────────────────────────────────────────────
(gen_random_uuid(), 'Bandoneón', 'Bandoneón', 'Aerophone', '412.132', 'A type of concertina central to Argentine Tango. Its melancholic sound defines the classic tango orchestra.', 'South America', ARRAY['metal reeds','wood'], 'Bandoneon', now(), now()),
(gen_random_uuid(), 'Charango', 'Charango', 'Chordophone', '321.322', 'A small South American lute from the Andes, traditionally made from armadillo shell. Central to Andean folk music.', 'South America', ARRAY['armadillo shell','wood','nylon'], 'Charango', now(), now()),
(gen_random_uuid(), 'Quena', 'Quena', 'Aerophone', '421.111.12', 'An Andean notched flute, one of the most ancient instruments of South America. Central to Andean traditional music.', 'South America', ARRAY['bamboo','cane','bone'], 'Quena', now(), now()),
(gen_random_uuid(), 'Cavaquinho', 'Cavaquinho', 'Chordophone', '321.322', 'A small Brazilian four-stringed instrument related to the ukulele. Used in Samba, Choro, and Fado music.', 'South America', ARRAY['spruce','rosewood'], 'Cavaquinho', now(), now()),
(gen_random_uuid(), 'Cuíca', 'Cuíca', 'Membranophone', '211.22', 'A Brazilian friction drum with a bamboo stick attached to the membrane, producing an unmistakable whining sound central to Samba.', 'South America', ARRAY['metal','cowhide','bamboo'], 'Cuíca', now(), now()),
(gen_random_uuid(), 'Pandeiro', 'Pandeiro', 'Membranophone', '211.311', 'A Brazilian frame drum (similar to a tambourine) central to Samba, Forró, and Choro music.', 'South America', ARRAY['wood','nylon skin','metal jingles'], 'Pandeiro', now(), now()),
(gen_random_uuid(), 'Zampoña', 'Zampoña', 'Aerophone', '421.112.2', 'A pan pipe from the Andes played since pre-Incan times. Also called siku. Central to Andean folk music ensembles.', 'South America', ARRAY['bamboo','cane'], 'Siku_(instrument)', now(), now()),

-- ── Caribbean ─────────────────────────────────────────────────────────────────
(gen_random_uuid(), 'Steel Pan', 'Steel Pan', 'Idiophone', '111.241.2', 'A percussion instrument originating in Trinidad and Tobago in the 1930s, made from oil drums. Central to Calypso and Soca music.', 'Caribbean', ARRAY['steel oil drums'], 'Steel_pan', now(), now()),
(gen_random_uuid(), 'Nyahbinghi Drum', 'Nyahbinghi', 'Membranophone', '211.212.1', 'Sacred Rastafarian drums used in ceremonial music. The bass, funde (mid), and repeater drums form the trinity central to Reggae.', 'Caribbean', ARRAY['wood','goatskin'], 'Nyahbinghi', now(), now()),

-- ── Oceania ───────────────────────────────────────────────────────────────────
(gen_random_uuid(), 'Didgeridoo', 'Yidaki', 'Aerophone', '423.121.2', 'A wind instrument developed by Indigenous Australians of northern Australia. One of the world''s oldest wind instruments, at least 1,500 years old.', 'Oceania', ARRAY['eucalyptus','termite-hollowed wood'], 'Didgeridoo', now(), now()),
(gen_random_uuid(), 'Pahu', 'Pahu', 'Membranophone', '211.261.1', 'A large Polynesian drum carved from a hollow log, covered with sharkskin. Central to Hawaiian hula and other Polynesian ceremonial music.', 'Oceania', ARRAY['coconut wood','sharkskin'], 'Pahu', now(), now()),
(gen_random_uuid(), 'Nose Flute', 'Nguru', 'Aerophone', '421.111.12', 'A flute played using nasal breath, found across Polynesia including New Zealand (Māori nguru) and Hawaii. Considered the breath of the spirit.', 'Oceania', ARRAY['wood','bone'], 'Nose_flute', now(), now()),

-- ── Central Asia ──────────────────────────────────────────────────────────────
(gen_random_uuid(), 'Dombra', 'Домбра', 'Chordophone', '321.321', 'A long-necked two-stringed lute central to Kazakh folk music. Central to Kazakh oral epic poetry performance.', 'Central Asia', ARRAY['birch','spruce'], 'Dombra', now(), now()),
(gen_random_uuid(), 'Morin Khuur', 'Морин хуур', 'Chordophone', '321.322', 'The Mongolian horsehead fiddle — a spike fiddle with a carved horse head. Central to Mongolian nomadic music and throat singing.', 'Central Asia', ARRAY['wood','horsehair','pine'], 'Morin_khuur', now(), now()),
(gen_random_uuid(), 'Rubab', 'رباب', 'Chordophone', '321.321', 'A short-necked lute from Afghanistan considered the national instrument. Central to Hindustani classical and Afghan folk music.', 'Central Asia', ARRAY['mulberry','goatskin'], 'Rubab_(instrument)', now(), now())

ON CONFLICT (name) DO NOTHING;
